namespace Paladin.Api.Dto.Environments
{
    public enum EnemyType
    {
        Slime,
        Shopkeeper,
        Conjurer,
        BatMiniboss,
        Bat,
        Monkey,
        Skeleton,
        Crate,
        Zombie,
        Medic,
        Bossmaster,
        Merlin,
        Hephaestus,
        Beastmaster,
        Trainer,
        Janitor,
        DiamondDealer,
        Weaponmaster,
        Pawnbroker,
        Minotaur,
        Dragon,
        Ghost,
        Wraith
    }
}
